### ISSUE TITLE
Web Services Explorer error 500 (again in 2024 ???)

### ISSUE THREAD

**Issue by OlivierJ1** [eclipse-webservices/webservices#2]
Hello,

**Impossible to launch the Web Service Explorer in Eclipse** // Eclipse WTP / JSDK 1.7, 1.8, 21 // Win 11.
Each time I launch the Web Service Explorer it ends with:

*HTTP ERROR 500 javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat
URI: /wse/wsexplorer/wsexplorer.jsp 
STATUS: 500 
MESSAGE: javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat SERVLET: org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet-f345f12 
CAUSED BY: javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat CAUSED BY: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat 
CAUSED BY: java.lang.ClassNotFoundException: org.apache.el.util.JreCompat cannot be found by org.mortbay.jasper.apache-jsp_9.0.52 Caused by: javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:332) .../...*

Other info: Windows 11 within Parallel Desktop on macOS Sonoma 14.1.2.

I am using **Eclipse IDE for Enterprise Java and Web Developers** (includes Incubating components) || **Version: 2023-12 (4.30.0) || Build id: 20231201-2043. Plug-ins: Web Tools Platform (WTP)** || software repository: download.eclipse.org/webtools/repository/latest](https://download.eclipse.org/webtools/repository/latest 

I tried with JSDK 1.7, 1.8, 17 & 21.

I reinstalled Eclipse 3 times, from both Java IDE version and WTP IDE. 
I tried to solve the issue installing several plug-ins from Eclipse repository. 
I added tomcat-util-9.0.0.M9.jar as external jar to the JREs (I searched for a solution w/ google and found that this may solve the issue).

... always the same result.

//--------------------------------------------------------
I also did a fresh install on MacOS with "Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components) | Version: 2023-12 (4.30.0) | Build id: 20231201-2043" that I downloaded from this URL :
"[eclipse.org/downloads/download.php?file=/technology/epp/…](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2023-12/R/eclipse-jee-2023-12-R-macosx-cocoa-aarch64.dmg)" 
that I found at: 
[eclipse.org/downloads/packages](https://www.eclipse.org/downloads/packages/) 

Same issue: HTTP ERROR 500 javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat URI: /wse/wsexplorer/wsexplorer.jsp STATUS: 500

**Comment by nitind** [comment]
Looks like the Eclipse 4.30 release left out the org.mortbay.jasper.apache-el bundle, but it's now part of the 4.31 builds, meaning the packages at https://www.eclipse.org/downloads/packages/release/2024-03/m2 are already corrected.

**Comment by OlivierJ1** [comment]
Thank you !

 

 

 

-

 

 

From: Nitin Dahyabhai ***@***.***>
Reply to: eclipse-webservices/webservices ***@***.***>
Date: Tuesday 13 February 2024 at 03:08
To: eclipse-webservices/webservices ***@***.***>
Cc: OlivierJ1 ***@***.***>, Author ***@***.***>
Subject: Re: [eclipse-webservices/webservices] Web Services Explorer error 500 (again in 2024 ???) (Issue #2)

 

Looks like the Eclipse 4.30 release left out the org.mortbay.jasper.apache-el bundle, but it's now part of the 4.31 builds, meaning the packages at https://www.eclipse.org/downloads/packages/release/2024-03/m2 are already corrected.
